USE [master]
ALTER DATABASE [AdventureWorksDW2017] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
RESTORE DATABASE [AdventureWorksDW2017] 
FROM  DISK = N'C:\Temp\AdventureWorksDW2017.BAK' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
GO


